-- return {
--     "ray-x/navigator.lua",
--     dependencies = {
--       {
--         "hrsh7th/nvim-cmp",
--         config = function()
--           local cmp = require("cmp")
--           local luasnip = require("luasnip")
--           local lspkind = require("lspkind")
  
--           cmp.setup({
--             snippet = {
--               expand = function(args)
--                 luasnip.lsp_expand(args.body)
--               end,
--             },
--             mapping = cmp.mapping.preset.insert({
--               ["<C-Space>"] = cmp.mapping.complete(),
--               ["<CR>"] = cmp.mapping.confirm({ select = false }),
--               ["<Tab>"] = cmp.mapping(function(fallback)
--                 if cmp.visible() then
--                   cmp.select_next_item()
--                 elseif luasnip.expand_or_jumpable() then
--                   luasnip.expand_or_jump()
--                 else
--                   fallback()
--                 end
--               end, { "i", "s" }),
--             }),
--             sources = cmp.config.sources({
--               { name = "nvim_lsp" },
--               { name = "luasnip" },
--               { name = "path" },
--             }),
--             formatting = {
--               format = lspkind.cmp_format({
--                 mode = "symbol_text",
--                 maxwidth = 50,
--               }),
--             },
--             experimental = { ghost_text = true },
--           })
--         end,
--       },
--       "hrsh7th/cmp-nvim-lsp",
--       "hrsh7th/cmp-path",
--       "saadparwaiz1/cmp_luasnip",
--       "L3MON4D3/LuaSnip",
--       "onsails/lspkind-nvim",
  
--       -- Syntax highlighting
--       { "nvim-treesitter/nvim-treesitter" },
  
--       -- GUI backend for navigator
--       {
--         "ray-x/guihua.lua",
--         run = "cd lua/fzy && make"
--       },
  
--       -- Go tools
--       {
--         "ray-x/go.nvim",
--         event = { "CmdlineEnter" },
--         ft = { "go", "gomod" },
--         build = ':lua require("go.install").update_all_sync()'
--       },
  
--       -- Signature help
--       {
--         "ray-x/lsp_signature.nvim",
--         event = "VeryLazy",
--         config = function()
--           require("lsp_signature").setup()
--         end
--       },
--     },
--     config = function()
--       require("go").setup()
  
--       require("navigator").setup({
--         lsp_signature_help = true,
--         lsp = {
--           format_on_save = true,
--           servers = { "gopls" },
--         },
--       })
  
--       vim.api.nvim_create_autocmd("FileType", {
--         pattern = { "go" },
--         callback = function()
--           local opts = { noremap = true, silent = true }
--           vim.api.nvim_buf_set_keymap(0, "n", "<C-i>", ":GoImports<CR>", opts)
--           vim.api.nvim_buf_set_keymap(0, "n", "<C-l>", ":GoRmTag json,yaml,validate<CR>", opts)
--           vim.api.nvim_buf_set_keymap(0, "n", "<C-j>", ":GoAddTag<CR>", opts)
--           vim.api.nvim_buf_set_keymap(0, "n", "<C-y>", ":GoAddTag yaml<CR>", opts)
--           vim.api.nvim_buf_set_keymap(0, "n", "<C-r>", ":GoAddTag validate:required<CR>", opts)
--           vim.api.nvim_buf_set_keymap(0, "n", "<C-b>", ":GoBuild %:h<CR>", opts)
--           vim.api.nvim_buf_set_keymap(0, "n", "<C-t>", ":GoTestPkg<CR>", opts)
--           vim.api.nvim_buf_set_keymap(0, "n", "<C-c>", ":GoCoverage -p<CR>", opts)
  
--           vim.api.nvim_buf_set_keymap(0, "n", "A", ":lua require('go.alternate').switch(true, '')<CR>", opts)
--           vim.api.nvim_buf_set_keymap(0, "n", "V", ":lua require('go.alternate').switch(true, 'vsplit')<CR>", opts)
--           vim.api.nvim_buf_set_keymap(0, "n", "S", ":lua require('go.alternate').switch(true, 'split')<CR>", opts)
--         end,
--         group = vim.api.nvim_create_augroup("go_autocommands", { clear = true }),
--       })
--     end,
--   }
  